### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Ryeera** [robrotheram/go-watch2gether#10]
Hi! I'd love to test your project, but unfortunately, I can't get it to run. If I try just running the command you provided, it fails to start because it tries to register Discord-Commands even though I have not provided any credentials. If I have a look at the docker-compose file, I don't know what I have to put into some fields. It would be great if there was some documentation for how to actually get this to run. Hopefully you can help, thank you!

**Comment by robrotheram** [comment]
Hi @Ryeera 
I have updated the Readme with some more guidance on how to create a discord client

**Comment by Ryeera** [comment]
Thanks so much, that really helped! I'll try to set it up again tomorrow with that ^^
